'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const E=require('../survivor/web/static/draft-engine.js');
function fixture(){
 const rows=Array.from({length:60},(_,i)=>({player_id:'p'+i,player:'Player '+i,positions:i%2?'PG,SG':'PF,C',nba_team:'NBA',fair_value:Math.max(0,70-i*1.4),expected_auction_price:Math.max(1,64-i),games:70,minutes_pg:30,pts_pg:20,reb_pg:6,ast_pg:4,stl_pg:1,blk_pg:1,fg3m_pg:2,fgm_pg:7,fga_pg:14,ftm_pg:4,fta_pg:5,z:Object.fromEntries(E.CATS.map((k,j)=>[k,((i+j)%7-3)/2]))}));
 const keepers={season:'2026-27',budget_per_team:200,teams:['Max','A','B'].map(franchise=>({franchise,budget_per_team:200})),rows:['Max','A','B'].map((franchise,i)=>({franchise,player_id:'p'+(57+i),keeper_cost:10}))};
 const s=E.create(rows,keepers,{id:'test',mode:'live',runId:'frozen-run'});s.settings.rosterSize=5;return s;
}
let next=0;const ev=(type,props={})=>({id:'e'+(++next),type,...props,at:'2026-10-09T12:00:00Z',source:'test'});
test('keeper budgets and minimum reserves determine legal maximum',()=>{const s=fixture(),st=E.replay(s);assert.equal(E.legalMax(st,'Max'),187);assert.equal(E.board(st,'Max').market.remaining,570);assert.equal(E.board(st,'Max').rows.length,57);});
test('opening live prices preserve saved expected prices',()=>{const s=fixture(),b=E.board(E.replay(s),'Max');assert.equal(b.rows[0].market.expected,b.rows[0].expected_auction_price);});
test('duplicate delivery is idempotent and conflicting reuse is rejected',()=>{const s=fixture(),e=ev('nominate',{playerId:'p0'});E.append(s,e);E.append(s,e);assert.equal(s.events.length,1);assert.throws(()=>E.append(s,{...e,playerId:'p1'}),/reused/);});
test('every bidder remains in history after a sale and only sale changes cash',()=>{const s=fixture();E.append(s,ev('nominate',{playerId:'p0'}));E.append(s,ev('bid',{playerId:'p0',team:'Max',amount:20}));let st=E.append(s,ev('bid',{playerId:'p0',team:'A',amount:21}));assert.equal(st.teams.Max.remaining,190);st=E.append(s,ev('sale',{playerId:'p0',team:'A',amount:21}));assert.equal(st.teams.A.remaining,169);assert.equal(st.teams.Max.remaining,190);assert.equal(st.bids.length,2);assert.equal(st.nomination,null);assert.equal(st.samples.length,1);});
test('bid ladder does not train the price model',()=>{const s=fixture();E.append(s,ev('nominate',{playerId:'p0'}));for(let i=1;i<20;i++)E.append(s,ev('bid',{playerId:'p0',team:i%2?'Max':'A',amount:i}));const st=E.replay(s);assert.equal(st.samples.length,0);assert.equal(E.market(st,s.players[1]).expected,s.players[1].expected_auction_price);});
test('a cheap sale leaves more cash against the remaining talent',()=>{const cheap=fixture(),expensive=fixture();E.append(cheap,ev('sale',{playerId:'p0',team:'A',amount:10}));E.append(expensive,ev('sale',{playerId:'p0',team:'A',amount:100}));assert.ok(E.board(E.replay(cheap),'Max').market.pressure>E.board(E.replay(expensive),'Max').market.pressure);assert.ok(E.market(E.replay(cheap),cheap.players[50]).expected>E.market(E.replay(expensive),expensive.players[50]).expected);});
test('similar-player demand adjusts gently after one overpay',()=>{const s=fixture();const st=E.append(s,ev('sale',{playerId:'p0',team:'A',amount:100})),m=E.market(st,s.players[2]);assert.ok(m.tierFactor>1);assert.ok(m.tierFactor<1.15);assert.equal(m.confidence,'Early estimate');});
test('outlier prices do not overwhelm the prior',()=>{const s=fixture();const st=E.append(s,ev('sale',{playerId:'p20',team:'A',amount:187}));assert.ok(E.market(st,s.players[22]).tierFactor<=1.11);});
test('one confirmed sale yields one training sample, recovered history yields none',()=>{const s=fixture();E.append(s,ev('sale',{playerId:'p0',team:'A',amount:30,recovered:true}));const st=E.replay(s);assert.equal(st.teams.A.remaining,160);assert.equal(st.samples.length,0);assert.equal(st.sales[0].expectedBefore,null);});
test('historic losing bids never overwrite the current nomination',()=>{const s=fixture();E.append(s,ev('nominate',{playerId:'p0'}));const st=E.append(s,ev('bid',{playerId:'p1',team:'B',amount:15,history:true}));assert.equal(st.nomination.playerId,'p0');assert.equal(st.nomination.amount,0);assert.equal(st.bids.length,1);});
test('observed lower bids cannot roll back a leader',()=>{const s=fixture();E.append(s,ev('nominate',{playerId:'p0'}));E.append(s,ev('bid',{playerId:'p0',team:'A',amount:40}));const st=E.append(s,ev('bid',{playerId:'p0',team:'B',amount:30}));assert.equal(st.nomination.leader,'A');assert.equal(st.bids.length,2);});
test('illegal spending, unknown identities and duplicate sales are atomic failures',()=>{const s=fixture();assert.throws(()=>E.append(s,ev('sale',{playerId:'p0',team:'A',amount:188})),/budget/);assert.equal(s.events.length,0);assert.throws(()=>E.append(s,ev('sale',{playerId:'unknown',team:'A',amount:1})),/Match/);assert.throws(()=>E.append(s,ev('sale',{playerId:'p0',team:'Nobody',amount:1})),/Match/);E.append(s,ev('sale',{playerId:'p0',team:'A',amount:30}));assert.throws(()=>E.append(s,ev('sale',{playerId:'p0',team:'B',amount:31})),/rostered/);assert.equal(s.events.length,1);});
test('undo replays budgets, availability, market and leader from history',()=>{const s=fixture();E.append(s,ev('nominate',{playerId:'p0'}));E.append(s,ev('bid',{playerId:'p0',team:'A',amount:35}));const sale=ev('sale',{playerId:'p0',team:'A',amount:35});E.append(s,sale);const st=E.append(s,ev('undo',{targetId:sale.id}));assert.equal(st.teams.A.remaining,190);assert.equal(st.nomination.amount,35);assert.equal(st.samples.length,0);assert.ok(E.board(st,'Max').rows.some(p=>p.player_id==='p0'));});
test('reconnect/export replay exactly reproduces state',()=>{const s=fixture();E.append(s,ev('sale',{playerId:'p0',team:'A',amount:35}));E.append(s,ev('nominate',{playerId:'p1'}));assert.deepEqual(E.board(E.replay(JSON.parse(JSON.stringify(s))),'Max'),E.board(E.replay(s),'Max'));});
test('practice session cannot mutate the live session or saved projections',()=>{const s=fixture(),before=JSON.stringify(s),practice=JSON.parse(before);practice.mode='practice';E.append(practice,ev('sale',{playerId:'p0',team:'A',amount:35}));assert.equal(JSON.stringify(s),before);assert.deepEqual(practice.players,s.players);});
test('team interest separates observed bidders from predictions',()=>{const s=fixture();E.append(s,ev('nominate',{playerId:'p0'}));E.append(s,ev('bid',{playerId:'p0',team:'B',amount:20}));E.append(s,ev('bid',{playerId:'p0',team:'A',amount:21}));const b=E.board(E.replay(s),'Max');assert.equal(b.teams.find(t=>t.name==='A').interest,'Leading');assert.equal(b.teams.find(t=>t.name==='B').interest,'Has bid');assert.notEqual(b.teams.find(t=>t.name==='Max').interest,'Has bid');});
test('recommended cap obeys reserve and minimum roster fill',()=>{const s=fixture();s.settings.reservePerSlot=50;const b=E.board(E.replay(s),'Max');assert.ok(b.rows.every(p=>p.fit.cap<=40));});
test('a leading user gets HOLD and expensive next bid gets PASS',()=>{const s=fixture();E.append(s,ev('nominate',{playerId:'p0'}));E.append(s,ev('bid',{playerId:'p0',team:'Max',amount:20}));assert.equal(E.board(E.replay(s),'Max').decision,'HOLD');E.append(s,ev('bid',{playerId:'p0',team:'A',amount:187}));assert.equal(E.board(E.replay(s),'Max').decision,'PASS');});
test('position matching uses flexible assignment, not greedy first position',()=>{assert.equal(E.canFit([{positions:'PG,SG'},{positions:'PG'}],['PG','SG']),true);assert.equal(E.canFit([{positions:'C'},{positions:'C'}],['PG','C']),false);assert.equal(E.canFit([{positions:'C'},{positions:'C'}],[]),true);});
test('filled teams have zero legal max; slot mismatch cannot be recommended',()=>{const s=fixture();s.settings.rosterSize=1;let st=E.replay(s);assert.equal(E.legalMax(st,'Max'),0);assert.ok(E.board(st,'Max').rows.every(p=>p.fit.cap===0));});
test('shooting fit aggregates makes and attempts weighted by projected games',()=>{const s=fixture();s.players[57].fgm_pg=1;s.players[57].fga_pg=2;s.players[57].games=20;s.players[0].fgm_pg=9;s.players[0].fga_pg=10;s.players[0].games=80;const f=E.fit(E.replay(s),s.players[0],'Max');assert.equal(f.fgBefore,.5);assert.equal(f.fgAfter,740/840);assert.notEqual(f.fgAfter,.7);});
test('ambiguous and similar names are never fuzzy matched',()=>{const s=fixture();s.players[0].player='Jalen Williams';s.players[1].player='Jaylin Williams';assert.equal(E.resolvePlayer(s,'Jalen Williams'),'p0');assert.equal(E.resolvePlayer(s,'J. Williams'),null);});
test('noninteger or below-minimum bids are rejected',()=>{for(const amount of [0,-1,1.5,NaN,Infinity,'10']){const s=fixture();assert.throws(()=>E.append(s,ev('sale',{playerId:'p0',team:'A',amount})));}});
test('corrupt imports and invalid roster settings are rejected',()=>{const s=fixture();assert.throws(()=>E.replay({...s,version:2}));assert.throws(()=>E.replay({...s,settings:{...s.settings,rosterSlots:['C']}}));const e=ev('nominate',{playerId:'p0'});assert.throws(()=>E.replay({...s,events:[e,e]}),/Duplicate/);assert.throws(()=>E.append(s,ev('undo',{targetId:'missing'})),/earlier/);});

test('a new nomination cannot silently erase an unconfirmed previous result',()=>{const s=fixture();E.append(s,ev('nominate',{playerId:'p0'}));E.append(s,ev('bid',{playerId:'p0',team:'A',amount:40}));assert.throws(()=>E.append(s,ev('nominate',{playerId:'p1'})),/previous nomination/);assert.equal(E.replay(s).nomination.playerId,'p0');E.append(s,ev('sale',{playerId:'p0',team:'A',amount:40}));E.append(s,ev('nominate',{playerId:'p1'}));assert.equal(E.replay(s).nomination.playerId,'p1');});
