const test=require('node:test');
const assert=require('node:assert/strict');
const E=require('../survivor/web/static/draft-engine.js');
const M=require('../survivor/web/static/draft-practice.js');
function fixture() {
  const players=Array.from({length:20},(_,i)=>({player_id:'p'+i,player:'Player '+String(i).padStart(2,'0'),positions:i%2?'C':'PG',nba_team:'X',games:70,minutes_pg:30,
    pts_pg:25-i,reb_pg:5,ast_pg:5,stl_pg:1,blk_pg:1,fg3m_pg:2,fgm_pg:7,fga_pg:15,ftm_pg:4,fta_pg:5,
    fair_value:40-i,expected_auction_price:30-i,z:Object.fromEntries(E.CATS.map(k=>[k,(10-i)/10]))}));
  return {version:1,id:'mock-test',mode:'practice',season:'2026-27',createdAt:'2026-10-09T00:00:00Z',baselineRunId:'test',players,
    teams:['Max','A','B'].map(name=>({name,budget:100})),keepers:[],events:[],settings:{rosterSize:3,minimumBid:1,reservePerSlot:1,rosterSlots:[]}};
}
test('practice rejects a live session without changing it',()=>{const s=fixture();s.mode='live';const before=JSON.stringify(s);assert.throws(()=>new M.Auction(s,'Max'),/practice/);assert.equal(JSON.stringify(s),before);});
test('nominations follow neutral value, exclude keepers and begin without seeded sales',()=>{const s=fixture();s.keepers=[{playerId:'p0',team:'A',amount:10,keeper:true}];const a=new M.Auction(s,'Max');assert.equal(a.snapshot.nomination.playerId,'p1');assert.equal(a.snapshot.sales.length,0);assert.equal(a.state.remainingMs,10000);assert.equal(a.running,false);});
test('the ten-second deadline records exactly one sale at the observed winning bid',()=>{const a=new M.Auction(fixture(),'Max');a.start();a.advance(9999);assert.equal(a.snapshot.sales.length,0);const lead={...a.snapshot.nomination};assert.ok(lead.amount>0);a.advance(1);assert.equal(a.snapshot.sales.length,1);assert.equal(a.snapshot.sales[0].amount,lead.amount);assert.equal(a.snapshot.sales[0].team,lead.leader);assert.equal(a.state.phase,'result');assert.equal(a.snapshot.teams[lead.leader].remaining,100-lead.amount);assert.equal(a.snapshot.samples.length,1);a.advance(1799);assert.equal(a.snapshot.nomination,null);a.advance(1);assert.equal(a.snapshot.nomination.playerId,'p1');assert.equal(a.snapshot.sales.length,1);});
test('only the user can bid for their selected team and a user bid never resets the clock',()=>{const a=new M.Auction(fixture(),'Max');a.start();a.advance(5000);assert.ok(a.snapshot.bids.length>2);assert.ok(a.snapshot.bids.every(b=>b.team!=='Max'));a.bid(98);assert.equal(a.state.remainingMs,5000);assert.equal(a.snapshot.nomination.leader,'Max');assert.throws(()=>a.bid(99),/highest/);assert.throws(()=>a.pass(),/committed/);a.advance(5000);assert.equal(a.snapshot.sales[0].team,'Max');assert.equal(a.snapshot.teams.Max.remaining,2);});
test('pause and JSON restoration preserve time without background sales',()=>{const s=fixture(),a=new M.Auction(s,'Max');a.start();a.advance(2400);a.pause();const before=JSON.stringify(s);a.advance(60000);assert.equal(JSON.stringify(s),before);const restored=new M.Auction(JSON.parse(before),'Max');assert.equal(restored.running,false);assert.equal(restored.state.remainingMs,7600);restored.start();restored.advance(7600);assert.equal(restored.snapshot.sales.length,1);});
test('pass blocks user bids until rejoining and other teams keep bidding',()=>{const a=new M.Auction(fixture(),'Max');a.start();a.pass();assert.throws(()=>a.bid(1),/Rejoin/);a.advance(1000);assert.ok(a.snapshot.bids.length);a.pass();a.bid(a.snapshot.nomination.amount+1);assert.equal(a.snapshot.nomination.leader,'Max');});
test('user bids obey minimums, available cash, slots, pause and deadlines',()=>{const a=new M.Auction(fixture(),'Max');assert.throws(()=>a.bid(1),/Start/);a.start();for(const amount of [0,1.5,99,Infinity])assert.throws(()=>a.bid(amount));a.advance(10000);assert.throws(()=>a.bid(1),/Start/);});
test('bot bids respect position eligibility and minimum roster reserves',()=>{const s=fixture();s.settings.rosterSize=2;s.settings.rosterSlots=['PG','C'];s.keepers=[{playerId:'p2',team:'A',amount:96,keeper:true},{playerId:'p4',team:'B',amount:96,keeper:true}];const a=new M.Auction(s,'Max');a.start();a.advance(10000);assert.equal(a.snapshot.bids.length,0);assert.equal(a.state.lastResult.team,null);a.advance(1800);assert.equal(a.snapshot.nomination.playerId,'p1');a.advance(10000);assert.ok(a.snapshot.bids.length);assert.ok(a.snapshot.bids.every(b=>b.amount<=4));assert.equal(a.snapshot.sales.length,1);});
test('a complete mock fills all rosters, preserves money and never changes forecast inputs',()=>{const s=fixture(),baseline=JSON.stringify(s.players),a=new M.Auction(s,'Max');a.start();for(let i=0;i<40&&a.state.phase!=='complete';i++){if(a.state.phase==='result'){a.advance(1800);continue;}a.advance(9000);if(a.snapshot.nomination&&E.legalMax(a.snapshot,'Max')>=Math.max(1,a.snapshot.nomination.amount+1)&&a.snapshot.nomination.leader!=='Max')a.bid(Math.max(1,a.snapshot.nomination.amount+1));a.advance(1000);}assert.equal(a.state.phase,'complete');assert.equal(a.snapshot.sales.length,9);assert.ok(Object.values(a.snapshot.teams).every(t=>t.roster.length===3&&t.remaining>=0));assert.equal(a.snapshot.sales.reduce((n,s)=>n+s.amount,0)+Object.values(a.snapshot.teams).reduce((n,t)=>n+t.remaining,0),300);assert.equal(JSON.stringify(s.players),baseline);assert.equal(new Set(a.snapshot.sales.map(s=>s.playerId)).size,9);});
test('unsold players are not looped forever when only the user can take them',()=>{const s=fixture();s.teams=[s.teams[0]];s.settings.rosterSize=1;const a=new M.Auction(s,'Max');a.start();a.advance(20*(10000+1800));assert.equal(a.state.phase,'complete');assert.equal(a.snapshot.sales.length,0);assert.equal(a.snapshot.teams.Max.remaining,100);});
