"""Postgres is the runtime database; SQLite exists only in memory for previews/tests."""
from __future__ import annotations

import os
from pathlib import Path
import sqlite3

SCHEMA = Path(__file__).with_name('schema.sql')


class Record(dict):
    def __getitem__(self, key):
        if isinstance(key, int):
            return list(self.values())[key]
        return super().__getitem__(key)


class Cursor:
    def __init__(self, cursor):
        self.cursor = cursor
        self.description = cursor.description

    def fetchone(self):
        result = self.cursor.fetchone()
        return None if result is None else Record(result)

    def fetchall(self):
        return [Record(row) for row in self.cursor.fetchall()]

    def __iter__(self):
        return (Record(row) for row in self.cursor)


class Postgres:
    dialect = 'postgres'

    def __init__(self, url, *, initialize=True, readonly=False):
        import psycopg
        from psycopg.rows import dict_row
        options = '-c search_path=survivor -c statement_timeout=15000'
        if readonly:
            options += ' -c default_transaction_read_only=on'
        self.connection = psycopg.connect(url, row_factory=dict_row, connect_timeout=15, options=options)
        if initialize:
            with self.connection.transaction():
                self.connection.execute("SELECT pg_advisory_xact_lock(hashtext('survivor-schema'))")
                self.connection.execute('CREATE SCHEMA IF NOT EXISTS survivor')
                self.connection.execute('SET search_path TO survivor')
                self.connection.execute(SCHEMA.read_text(encoding='utf-8'))

    def execute(self, sql, parameters=None):
        if sql.startswith('INSERT OR IGNORE INTO '):
            sql = sql.replace('INSERT OR IGNORE INTO ', 'INSERT INTO ', 1) + ' ON CONFLICT DO NOTHING'
        return Cursor(self.connection.execute(sql.replace('?', '%s'), parameters))

    def executemany(self, sql, parameters):
        with self.connection.cursor() as cursor:
            cursor.executemany(sql.replace('?', '%s'), parameters)

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc, traceback):
        if exc_type:
            self.connection.rollback()
        else:
            self.connection.commit()

    def close(self):
        self.connection.close()


def preview_database(*, threaded=False):
    connection = sqlite3.connect(':memory:', check_same_thread=not threaded)
    connection.row_factory = sqlite3.Row
    connection.execute('PRAGMA foreign_keys=ON')
    schema = SCHEMA.read_text(encoding='utf-8')
    schema = schema.replace('INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY', 'INTEGER PRIMARY KEY')
    schema = schema.replace('CREATE OR REPLACE VIEW', 'CREATE VIEW IF NOT EXISTS')
    connection.executescript(schema)
    return connection


def railway_database(variable='DATABASE_URL'):
    url = os.environ.get(variable)
    if not url:
        raise ValueError(f'{variable} is not set. In Railway, reference the Postgres service DATABASE_URL. For an export-only preview use --preview.')
    if not url.startswith(('postgres://', 'postgresql://')):
        raise ValueError(f'{variable} must contain a PostgreSQL connection URL.')
    try:
        return Postgres(url)
    except ImportError as exc:
        raise ValueError('Install requirements.txt before connecting to Postgres.') from exc
    except Exception:
        # Driver messages can include connection details. Do not log the DSN.
        raise RuntimeError('Could not initialize Railway Postgres. Check the connection, permissions, and schema compatibility.') from None
