-- PostgreSQL schema. The importer uses the isolated 'survivor' namespace.
-- Preview/tests adapt this schema to in-memory SQLite; no local database file.

CREATE TABLE IF NOT EXISTS source_workbooks (
    source_id TEXT PRIMARY KEY, filename TEXT NOT NULL, sha256 TEXT NOT NULL,
    imported_at TEXT NOT NULL, metadata_json TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS source_sheets (
    source_id TEXT NOT NULL REFERENCES source_workbooks,
    sheet TEXT NOT NULL, sheet_index INTEGER NOT NULL, kind TEXT NOT NULL,
    max_row INTEGER NOT NULL, max_column INTEGER NOT NULL,
    populated_cells INTEGER NOT NULL, hidden_state TEXT NOT NULL,
    PRIMARY KEY (source_id, sheet)
);
CREATE TABLE IF NOT EXISTS raw_cells (
    source_id TEXT NOT NULL, sheet TEXT NOT NULL, coordinate TEXT NOT NULL,
    row_number INTEGER NOT NULL, column_number INTEGER NOT NULL,
    value_json TEXT, cached_value_json TEXT, data_type TEXT,
    style_id INTEGER, number_format TEXT, comment_text TEXT,
    PRIMARY KEY (source_id, sheet, coordinate),
    FOREIGN KEY (source_id, sheet) REFERENCES source_sheets
);
CREATE TABLE IF NOT EXISTS seasons (
    season TEXT PRIMARY KEY, league_year INTEGER UNIQUE NOT NULL,
    start_year INTEGER NOT NULL, mapping_basis TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS players (
    player_id TEXT PRIMARY KEY, display_name TEXT NOT NULL,
    nba_player_id TEXT UNIQUE, identity_status TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS player_aliases (
    raw_name TEXT PRIMARY KEY, player_id TEXT NOT NULL REFERENCES players,
    resolution_method TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS team_seasons (
    team_season_id TEXT PRIMARY KEY, source_id TEXT NOT NULL REFERENCES source_workbooks,
    season TEXT NOT NULL REFERENCES seasons, franchise_sheet TEXT NOT NULL,
    finish INTEGER, header_raw TEXT NOT NULL, header_row INTEGER NOT NULL,
    UNIQUE (source_id, season, franchise_sheet)
);
CREATE TABLE IF NOT EXISTS roster_entries (
    entry_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, team_season_id TEXT NOT NULL REFERENCES team_seasons,
    player_id TEXT NOT NULL REFERENCES players,
    stage TEXT NOT NULL CHECK(stage IN ('opening','final')),
    roster_order INTEGER NOT NULL, raw_name TEXT NOT NULL,
    recorded_cost NUMERIC(10,2) CHECK(recorded_cost >= 0), contract_year_recorded INTEGER,
    acquisition_class TEXT NOT NULL CHECK(acquisition_class IN ('auction','keeper','final_snapshot')),
    classification_basis TEXT NOT NULL, source_cell TEXT NOT NULL,
    cost_cell TEXT NOT NULL, contract_year_cell TEXT NOT NULL, note_raw TEXT,
    UNIQUE (team_season_id, stage, source_cell)
);
CREATE TABLE IF NOT EXISTS tracking_entries (
    tracking_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, source_id TEXT NOT NULL REFERENCES source_workbooks,
    season TEXT NOT NULL REFERENCES seasons, player_id TEXT NOT NULL REFERENCES players,
    raw_name TEXT NOT NULL, participant_raw TEXT NOT NULL, marker_raw TEXT NOT NULL,
    marker_number REAL, sheet TEXT NOT NULL, source_cell TEXT NOT NULL,
    UNIQUE (source_id, sheet, source_cell)
);
CREATE TABLE IF NOT EXISTS data_issues (
    issue_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, source_id TEXT NOT NULL REFERENCES source_workbooks,
    severity TEXT NOT NULL, code TEXT NOT NULL, season TEXT, sheet TEXT,
    source_cell TEXT, detail TEXT NOT NULL
);

-- Statistical inputs stay separate from paid salaries. All *_pg fields are per game.
CREATE TABLE IF NOT EXISTS stat_datasets (
    dataset_id TEXT PRIMARY KEY,
    kind TEXT NOT NULL CHECK(kind IN ('actual','projection')),
    season TEXT NOT NULL, source_name TEXT NOT NULL, source_url TEXT,
    as_of_date TEXT NOT NULL, imported_at TEXT NOT NULL, file_sha256 TEXT NOT NULL,
    coverage TEXT NOT NULL, notes TEXT
);
CREATE TABLE IF NOT EXISTS player_stats (
    dataset_id TEXT NOT NULL REFERENCES stat_datasets,
    player_id TEXT NOT NULL REFERENCES players, raw_name TEXT NOT NULL,
    nba_team TEXT, positions TEXT, games REAL NOT NULL CHECK(games >= 0),
    minutes_pg REAL NOT NULL CHECK(minutes_pg >= 0),
    pts_pg REAL NOT NULL CHECK(pts_pg >= 0), reb_pg REAL NOT NULL CHECK(reb_pg >= 0),
    ast_pg REAL NOT NULL CHECK(ast_pg >= 0), stl_pg REAL NOT NULL CHECK(stl_pg >= 0),
    blk_pg REAL NOT NULL CHECK(blk_pg >= 0), fg3m_pg REAL NOT NULL CHECK(fg3m_pg >= 0),
    fgm_pg REAL NOT NULL CHECK(fgm_pg >= 0), fga_pg REAL NOT NULL CHECK(fga_pg >= fgm_pg),
    ftm_pg REAL NOT NULL CHECK(ftm_pg >= 0), fta_pg REAL NOT NULL CHECK(fta_pg >= ftm_pg),
    CHECK(fg3m_pg <= fgm_pg), PRIMARY KEY(dataset_id, player_id)
);
CREATE TABLE IF NOT EXISTS valuation_runs (
    run_id TEXT PRIMARY KEY, projection_dataset_id TEXT NOT NULL REFERENCES stat_datasets,
    created_at TEXT NOT NULL, model_version TEXT NOT NULL,
    league_settings_json TEXT NOT NULL, training_cutoff TEXT NOT NULL,
    validation_json TEXT NOT NULL, notes TEXT
);
CREATE TABLE IF NOT EXISTS projected_values (
    run_id TEXT NOT NULL REFERENCES valuation_runs, player_id TEXT NOT NULL REFERENCES players,
    fair_value NUMERIC(10,2), expected_auction_price NUMERIC(10,2), recommended_bid_ceiling NUMERIC(10,2),
    lower_estimate NUMERIC(10,2), upper_estimate NUMERIC(10,2), keeper_cost NUMERIC(10,2), keeper_surplus NUMERIC(10,2),
    category_values_json TEXT NOT NULL, comps_json TEXT NOT NULL, risk_notes TEXT,
    PRIMARY KEY(run_id, player_id)
);
CREATE OR REPLACE VIEW roster_history AS
SELECT t.source_id, t.season, s.league_year, t.franchise_sheet, t.finish,
       p.display_name AS player, r.player_id, r.stage, r.roster_order,
       r.recorded_cost, r.contract_year_recorded, r.acquisition_class,
       r.raw_name, r.source_cell, r.cost_cell, r.contract_year_cell, r.note_raw
FROM roster_entries r JOIN team_seasons t USING(team_season_id)
JOIN seasons s USING(season) JOIN players p USING(player_id);
CREATE OR REPLACE VIEW auction_sales AS
SELECT h.* FROM roster_history h
WHERE h.acquisition_class = 'auction' AND h.recorded_cost > 0
AND h.contract_year_recorded = 1
AND NOT EXISTS (
    SELECT 1 FROM roster_history other
    WHERE other.source_id = h.source_id AND other.season = h.season
      AND other.player_id = h.player_id AND other.stage = 'opening'
      AND (other.franchise_sheet <> h.franchise_sheet OR other.source_cell <> h.source_cell)
);
CREATE OR REPLACE VIEW keeper_costs AS
SELECT * FROM roster_history WHERE acquisition_class = 'keeper';
CREATE OR REPLACE VIEW team_summary AS
SELECT t.source_id, t.season, t.franchise_sheet, t.finish,
       SUM(CASE WHEN r.stage='opening' THEN 1 ELSE 0 END) AS opening_players,
       SUM(CASE WHEN r.stage='final' THEN 1 ELSE 0 END) AS final_players,
       SUM(CASE WHEN r.acquisition_class='keeper' THEN 1 ELSE 0 END) AS keepers,
       SUM(CASE WHEN r.stage='opening' THEN r.recorded_cost ELSE 0 END) AS opening_cost,
       SUM(CASE WHEN r.acquisition_class='keeper' THEN r.recorded_cost ELSE 0 END) AS keeper_cost,
       SUM(CASE WHEN r.acquisition_class='auction' THEN r.recorded_cost ELSE 0 END) AS auction_cost
FROM team_seasons t JOIN roster_entries r USING(team_season_id)
GROUP BY t.team_season_id;
