"""Browser checks against a running dashboard preview; screenshots in artifacts/."""
import argparse
from pathlib import Path

from playwright.sync_api import expect, sync_playwright


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--url',default='http://127.0.0.1:8080')
    parser.add_argument('--browser')
    args=parser.parse_args()
    output=Path('artifacts')
    output.mkdir(exist_ok=True)
    with sync_playwright() as playwright:
        browser=playwright.chromium.launch(headless=True,executable_path=args.browser)
        context=browser.new_context(viewport={'width':1440,'height':1050},device_scale_factor=1)
        page=context.new_page()
        errors=[]
        page.on('pageerror',lambda error:errors.append(str(error)))
        page.goto(args.url,wait_until='networkidle')
        expect(page.locator('#results-count')).to_have_text('225')
        expect(page.locator('.stat-value').nth(1)).not_to_have_text('$0')
        page.screenshot(path=str(output/'dashboard-desktop.png'),full_page=False)
        page.locator('[data-kind="keeper"]').click()
        expect(page.locator('#results-count')).to_have_text('30')
        page.locator('#player-search').fill('Jokic')
        expect(page.locator('#results-count')).to_have_text('1')
        page.locator('#history-table .player-button').first.click()
        expect(page.locator('#player-name')).to_have_text('Nikola Jokic')
        expect(page.locator('#player-content')).to_contain_text('$85')
        expect(page.locator('#player-content')).to_contain_text('$84')
        expect(page.locator('.confirmed-keeper')).to_contain_text('Max · $88')
        page.screenshot(path=str(output/'dashboard-player.png'),full_page=True)
        page.keyboard.press('Escape')
        expect(page.locator('#player-dialog')).not_to_be_visible()
        page.locator('#season-select').select_option('all')
        page.locator('[data-kind="auction"]').click()
        expect(page.locator('#history-table')).to_contain_text('2024–25')
        expect(page.locator('#history-table')).not_to_contain_text('2025–26')
        page.locator('#player-search').fill('')
        expect(page.locator('#results-count')).to_have_text('2,173')
        expect(page.locator('.stat-value').first).to_have_text('2,173')
        with page.expect_download() as download:
            page.locator('#export-link').click()
        download.value.save_as(str(output/'browser-export.csv'))
        page.locator('[data-page="2"]').click()
        expect(page.locator('.pager')).to_contain_text('2 /')
        page.locator('[data-view="projections"]').click()
        expect(page.locator('#data-count')).to_have_text('318')
        expect(page.locator('.dataset-header')).to_contain_text('ESPN published projections')
        expect(page.locator('#projection-source-note')).to_have_count(0)
        expect(page.locator('.dataset-header a')).to_have_attribute('href','https://fantasy.espn.com/basketball/players/projections')
        expect(page.locator('#data-table')).not_to_contain_text('Nikola Jokic')
        page.screenshot(path=str(output/'dashboard-projections.png'),full_page=False)
        page.locator('#draft-filter').select_option('kept')
        expect(page.locator('#data-count')).to_have_text('30')
        page.locator('#data-search').fill('Jokic')
        expect(page.locator('#data-count')).to_have_text('1')
        expect(page.locator('#data-table')).to_contain_text('57.5%')
        expect(page.locator('#data-table')).to_contain_text('81.7%')
        page.locator('#data-table .player-button').click()
        expect(page.locator('#player-content')).to_contain_text('ESPN published projections')
        page.keyboard.press('Escape')
        page.set_viewport_size({'width':390,'height':844})
        expect(page.locator('#sidebar')).to_have_css('transform','matrix(1, 0, 0, 1, -244, 0)')
        assert page.evaluate('document.documentElement.scrollWidth <= window.innerWidth'), 'Projections overflow mobile'
        page.screenshot(path=str(output/'projections-mobile.png'),full_page=False,animations='disabled')
        page.set_viewport_size({'width':1440,'height':1050})
        page.locator('[data-view="valuations"]').click()
        expect(page.locator('#data-count')).to_have_text('318')
        expect(page.locator('#data-table thead')).to_contain_text('SURVIVOR VALUE')
        expect(page.locator('#data-table thead')).to_contain_text('EXPECTED LEAGUE PRICE')
        expect(page.locator('#data-table thead')).to_contain_text('NEUTRAL AUCTION VALUE')
        expect(page.locator('#data-table')).not_to_contain_text('Nikola Jokic')
        page.screenshot(path=str(output/'valuations-desktop.png'),full_page=False)
        expect(page.locator('#auction-market')).to_have_count(0)
        expect(page.locator('#valuation-method')).to_have_count(0)
        expect(page.locator('.valuation-guide')).to_have_count(0)
        page.locator('#data-position').select_option('SG')
        page.locator('#data-sort').select_option('fg_pct')
        page.locator('#data-direction').select_option('asc')
        cells=page.locator('#data-table tbody [data-label="FG%"]')
        percentages=[float(v) for v in cells.evaluate_all('(els)=>els.map(el=>el.dataset.value).filter(Boolean)')]
        assert percentages==sorted(percentages) and len(percentages)>5
        page.locator('#data-table [data-sort-key="fg_pct"]').click()
        descending=[float(v) for v in cells.evaluate_all('(els)=>els.map(el=>el.dataset.value).filter(Boolean)')]
        assert descending==list(reversed(percentages))
        page.locator('#data-columns').select_option('all')
        expect(page.locator('#data-table thead')).to_contain_text('PTS')
        expect(page.locator('#data-table thead')).to_contain_text('EXPECTED LEAGUE PRICE')
        page.locator('#data-position').select_option('')
        page.locator('#data-sort').select_option('survivor_score')
        page.locator('#data-columns').select_option('values')
        page.locator('#draft-filter').select_option('kept')
        expect(page.locator('#data-count')).to_have_text('30')
        with page.expect_download() as download:
            page.locator('#values-export').click()
        download.value.save_as(str(output/'browser-valuations.csv'))
        page.locator('#data-search').fill('Jokic')
        expect(page.locator('#data-count')).to_have_text('1')
        page.locator('#data-table .player-button').click()
        page.keyboard.press('Escape')
        page.locator('#data-table .price-comps-button').click()
        expect(page.locator('#player-comps')).to_be_focused()
        expect(page.locator('.comps-table').first).to_contain_text('Avg budget')
        expect(page.locator('.category-row')).to_have_count(8)
        # Qualified comp counts vary by player; no forced list of twenty.
        # Published archives must not be labelled as prior-season actuals.
        import json
        detail=page.request.get(args.url+'/api/players/nikolajokic').json()
        comps=json.loads(detail['valuations'][0]['comps_json'])
        expect(page.locator('.comps-table tbody tr')).to_have_count(len(comps))
        labels=page.locator('.comps-table tbody tr td:first-child small').all_text_contents()
        assert sum('projection' in label for label in labels)==sum(bool(c['forecast_dataset_id']) for c in comps)
        assert any(c['outlook_basis']=='published_projection' for c in comps)
        expect(page.locator('.comps-table tbody tr:visible')).to_have_count(min(5,len(comps)))
        expect(page.locator('.comp-weight')).to_have_count(len(comps))
        expect(page.locator('.comp-stats-table tbody tr')).to_have_count(1+min(3,len(comps)))
        expect(page.locator('.comp-target')).to_contain_text('Nikola Jokic')
        assert page.locator('.comp-stats-table').evaluate('(el) => el.scrollWidth <= el.parentElement.clientWidth'), 'Desktop comparison prices are clipped'
        expect(page.locator('.comp-price-breakdown')).to_contain_text('Weighted comp adjustment')
        market=json.loads(detail['valuations'][0]['category_values_json'])['market']
        expect(page.locator('.comp-price-breakdown')).to_contain_text(f"{market['correction_share']*100:.0f}% of final estimate")
        expect(page.locator('.comp-price-breakdown')).to_contain_text(f"{market['base_weight']*100:.0f}% of final estimate")
        expect(page.locator('.comp-summary')).to_contain_text('% of final price')
        expect(page.locator('.comp-weight small')).to_have_count(len(comps))
        page.locator('.comp-auction-context summary').click()
        expect(page.locator('.comp-context-table').first).to_contain_text('$2,210')
        largest=max(comps,key=lambda c:c['weight'])
        expect(page.locator('.comp-price-bridge tr').last).to_contain_text(f"${largest['implied_price']:.2f}")
        page.locator('.comp-auction-context summary').click()
        page.locator('.comps-table [data-sort-key="distance"]').first.click()
        distances=[float(t) for t in page.locator('.comps-table tbody tr td:nth-child(4)').all_text_contents()]
        assert distances==sorted(distances), 'Comp sorting must include the collapsed rows'
        page.locator('.comps-table [data-sort-key="weight"]').first.click()
        if len(comps)>5:
            page.locator('.remaining-comps summary').click()
            expect(page.locator('.comps-table tbody tr:visible')).to_have_count(len(comps))
            page.locator('.remaining-comps summary').click()
        page.locator('.comp-price-breakdown').scroll_into_view_if_needed()
        assert page.locator('.comps-table').first.evaluate('(el) => el.scrollWidth <= el.parentElement.clientWidth'), 'Desktop comparable adjustment column is hidden'
        page.screenshot(path=str(output/'valuation-weighted-comps.png'),full_page=False)
        expect(page.locator('.scenario-grid .projection-stat')).to_have_count(3)
        expect(page.locator('.valuation-metrics')).to_contain_text('IF AVAILABLE')
        page.screenshot(path=str(output/'valuation-player.png'),full_page=True)
        page.keyboard.press('Escape')
        page.locator('#data-search').fill('Brunson')
        expect(page.locator('#data-count')).to_have_text('1')
        page.locator('#data-table .price-comps-button').click()
        expect(page.locator('.comp-summary')).to_contain_text('1 near-identical forecast match')
        expect(page.locator('.comp-summary')).to_contain_text('95.0% of comps')
        expect(page.locator('.comp-summary')).to_contain_text('85.5% of final price')
        expect(page.locator('.comp-quality.near_identical')).to_have_count(1)
        expect(page.locator('.comp-quality.near_identical')).to_contain_text('Near-identical forecast')
        expect(page.locator('.comp-price-breakdown')).to_contain_text('90% of final estimate')
        expect(page.locator('.comp-price-breakdown')).to_contain_text('10% of final estimate')
        expect(page.locator('.comps-table tbody tr').first).to_contain_text('Jalen Brunson')
        expect(page.locator('.comps-table tbody tr').first).to_contain_text('$45')
        page.locator('.comp-price-breakdown').scroll_into_view_if_needed()
        page.screenshot(path=str(output/'brunson-near-identical-desktop.png'),full_page=False)
        page.set_viewport_size({'width':390,'height':844})
        expect(page.locator('.comp-summary')).to_contain_text('85.5% of final price')
        assert page.locator('#player-dialog').evaluate('(el) => el.scrollWidth <= el.clientWidth'), 'Near-identical summary overflows mobile dialog'
        page.locator('.comp-price-breakdown').scroll_into_view_if_needed()
        page.screenshot(path=str(output/'brunson-near-identical-mobile.png'),full_page=False)
        page.keyboard.press('Escape')
        page.locator('#data-search').fill('')
        page.set_viewport_size({'width':390,'height':844})
        expect(page.locator('#sidebar')).to_have_css('transform','matrix(1, 0, 0, 1, -244, 0)')
        assert page.evaluate('document.documentElement.scrollWidth <= window.innerWidth'), 'Valuations overflow mobile'
        page.screenshot(path=str(output/'valuations-mobile.png'),full_page=False,animations='disabled')
        page.set_viewport_size({'width':1440,'height':1050})
        page.locator('[data-view="rosters"]').click()
        page.locator('#season-select').select_option('2025-26')
        page.locator('#team-filter').select_option('Max')
        expect(page.locator('#results-count')).to_have_text('15')
        page.locator('[data-kind="final"]').click()
        expect(page.locator('#results-count')).to_have_text('17')
        page.locator('[data-view="notes"]').click()
        expect(page.locator('.issue-list .issue-row')).to_have_count(27)
        expect(page.locator('#historical-stats-status')).to_contain_text('12 seasons / 6,460 player-season records')
        page.locator('[data-view="keepers"]').click()
        expect(page.locator('.keeper-card')).to_have_count(15)
        expect(page.locator('.keeper-player')).to_have_count(30)
        expect(page.locator('.stat-value').nth(1)).to_have_text('$790')
        expect(page.locator('.stat-value').nth(2)).to_have_text('$2,210')
        expect(page.locator('.keeper-card').first).to_contain_text('Alvin')
        page.screenshot(path=str(output/'keepers-desktop.png'),full_page=True,animations='disabled')
        page.locator('#keeper-search').fill('Jokic')
        expect(page.locator('.keeper-card')).to_have_count(1)
        expect(page.locator('[data-franchise="Max"] .keeper-budget')).to_contain_text('$109')
        page.locator('#keeper-search').fill('')
        page.locator('#keeper-sort').select_option('team')
        expect(page.locator('.keeper-card').nth(1)).to_contain_text('Arthur')
        page.set_viewport_size({'width':390,'height':844})
        assert page.evaluate('document.documentElement.scrollWidth <= window.innerWidth'), 'Keeper page overflows mobile'
        page.screenshot(path=str(output/'keepers-mobile.png'),full_page=False,animations='disabled')
        page.locator('#menu-button').click()
        expect(page.locator('#sidebar')).to_have_class('sidebar open')
        page.locator('[data-view="history"]').click()
        expect(page.locator('#sidebar')).not_to_have_class('sidebar open')
        page.locator('#team-filter').select_option('')
        expect(page.locator('#results-count')).to_have_text('225')
        expect(page.locator('#nav-scrim')).not_to_be_visible()
        expect(page.locator('#sidebar')).to_have_css('transform','matrix(1, 0, 0, 1, -244, 0)')
        assert page.evaluate('document.documentElement.scrollWidth <= window.innerWidth'), 'Mobile layout overflows viewport'
        assert page.locator('#history-table .table-scroll').evaluate('(el) => el.scrollWidth <= el.clientWidth'), 'Mobile prices require sideways scrolling'
        page.screenshot(path=str(output/'dashboard-mobile.png'),full_page=True,animations='disabled')
        page.locator('#history-table .player-button').first.click()
        expect(page.locator('#player-dialog')).to_be_visible()
        expect(page.locator('#player-name')).not_to_have_text('Loading player…')
        page.locator('#close-player').click()
        expect(page.locator('#player-dialog')).not_to_be_visible()
        page.set_viewport_size({'width':1440,'height':1050})
        page.locator('[data-view="projections"]').click()
        datasets=page.request.get(args.url+'/api/bootstrap').json()['datasets']
        archive=next(d for d in datasets if d.get('coverage')=='partial_player_pool' and d['season']=='2025-26')
        page.locator('#dataset-select').select_option(archive['dataset_id'])
        expect(page.locator('#data-count')).to_have_text('200')
        expect(page.locator('.dataset-header')).to_contain_text('Received:')
        page.locator('#data-search').fill('Tatum')
        expect(page.locator('#data-count')).to_have_text('0')
        page.locator('#data-search').fill('Edwards')
        expect(page.locator('#data-count')).to_have_text('1')
        page.locator('#data-table .player-button').click()
        expect(page.locator('#player-content')).to_contain_text('No valuation for this projection set')
        expect(page.locator('#player-content')).to_contain_text('User-supplied 2025-26 projections')
        page.keyboard.press('Escape')
        published=next(d for d in datasets if d.get('date_basis')=='published' and d['season']=='2018-19')
        page.locator('#data-search').fill('')
        page.locator('#dataset-select').select_option(published['dataset_id'])
        expect(page.locator('#data-count')).to_have_text('154')
        expect(page.locator('.dataset-header')).to_contain_text('Razzball / Kostas')
        expect(page.locator('.dataset-header')).not_to_contain_text('Received:')
        page.locator('#data-search').fill('Jokic')
        expect(page.locator('#data-count')).to_have_text('1')
        page.locator('#data-table .player-button').click()
        expect(page.locator('#player-content')).to_contain_text('Razzball / Kostas')
        expect(page.locator('#player-content')).to_contain_text('No valuation for this projection set')
        page.keyboard.press('Escape')
        page.locator('#data-search').fill('')
        pdf=next(d for d in datasets if d.get('date_basis')=='published' and d['season']=='2024-25')
        page.locator('#dataset-select').select_option(pdf['dataset_id'])
        expect(page.locator('#data-count')).to_have_text('285')
        expect(page.locator('.dataset-header')).to_contain_text('NBC Sports / Rotoworld')
        # Synthetic data stays inside browser request interception; nothing is
        # written to the preview database or the production database.
        bootstrap=page.request.get(args.url+'/api/bootstrap').json()
        dataset={'dataset_id':'browser-test','kind':'projection','season':'2026-27','source_name':'SYNTHETIC BROWSER TEST','as_of_date':'2026-10-01','coverage':'full_season','players':1}
        run={'run_id':'browser-run','season':'2026-27','model_version':'test-only','source_name':'SYNTHETIC BROWSER TEST','created_at':'2026-10-02','players':1}
        bootstrap['datasets']=[dataset]
        bootstrap['runs']=[run]
        projection={'player_id':'nikolajokic','player':'Nikola Jokic','nba_team':'TEST','positions':'C','games':65,'minutes_pg':30,'pts_pg':20,'reb_pg':10,'ast_pg':3,'stl_pg':1,'blk_pg':2,'fg3m_pg':1,'fgm_pg':8,'fga_pg':15,'ftm_pg':3,'fta_pg':4,'draft_status':'kept','keeper_franchise':'Max','confirmed_keeper_cost':88}
        available_projection={**projection,'player_id':'giannisantetokounmpo','player':'Giannis Antetokounmpo','draft_status':'available','keeper_franchise':None,'confirmed_keeper_cost':None}
        valuation={'run_id':'browser-run','player_id':'nikolajokic','player':'Nikola Jokic','fair_value':90,'expected_auction_price':88,'recommended_bid_ceiling':None,'lower_estimate':80,'upper_estimate':95,'keeper_cost':85,'keeper_surplus':5,'draft_status':'kept','keeper_franchise':'Max','confirmed_keeper_cost':88,'category_values_json':'{"score":12.34}'}
        available_value={**valuation,'player_id':'giannisantetokounmpo','player':'Giannis Antetokounmpo','draft_status':'available','keeper_franchise':None,'confirmed_keeper_cost':None,'fair_value':65,'recommended_bid_ceiling':68}
        page.route('**/api/bootstrap',lambda route:route.fulfill(json=bootstrap))
        page.route('**/api/projections?*',lambda route:route.fulfill(json={'dataset':dataset,'rows':[projection,available_projection]}))
        page.route('**/api/valuations?*',lambda route:route.fulfill(json={'run':run,'rows':[valuation,available_value]}))
        page.set_viewport_size({'width':1440,'height':1050})
        page.goto(args.url+'/?browser-test=1#projections',wait_until='networkidle')
        expect(page.locator('#data-table')).to_contain_text('53.3%')
        expect(page.locator('#data-table')).to_contain_text('75.0%')
        expect(page.locator('#draft-filter')).to_have_value('available')
        expect(page.locator('#data-table')).not_to_contain_text('Nikola Jokic')
        expect(page.locator('#data-table')).to_contain_text('Giannis Antetokounmpo')
        page.locator('#draft-filter').select_option('kept')
        expect(page.locator('#data-table')).to_contain_text('Kept · Max · $88')
        expect(page.locator('#data-table')).not_to_contain_text('Giannis')
        page.locator('#draft-filter').select_option('all')
        expect(page.locator('#data-count')).to_have_text('2')
        page.locator('#data-search').fill('no-match')
        expect(page.locator('#data-table')).to_contain_text('No matching players')
        page.locator('[data-view="valuations"]').click()
        expect(page.locator('#draft-filter')).to_have_value('available')
        expect(page.locator('#data-table')).not_to_contain_text('Nikola Jokic')
        expect(page.locator('#data-table')).to_contain_text('$65')
        page.locator('#draft-filter').select_option('kept')
        expect(page.locator('#data-table')).to_contain_text('$90')
        expect(page.locator('#data-table')).to_contain_text('$88')
        expect(page.locator('#data-table tbody td').nth(1)).to_contain_text('12.34')
        expect(page.locator('#data-table tbody td').nth(3)).to_contain_text('$90')
        expect(page.locator('#dataset-select')).to_have_value('browser-run')
        player=page.request.get(args.url+'/api/players/nikolajokic').json()
        player['valuations']=[{**valuation,'season':'2026-27','risk_notes':'Synthetic browser test only'}]
        page.route('**/api/players/nikolajokic',lambda route:route.fulfill(json=player))
        page.locator('#data-table .player-button').click()
        expect(page.locator('#player-name')).to_have_text('Nikola Jokic')
        expect(page.locator('.valuation-metrics strong').nth(0)).to_have_text('12.34')
        expect(page.locator('.valuation-metrics strong').nth(2)).to_have_text('$90')
        expect(page.locator('#player-content')).to_contain_text('Keeper surplus $2')
        page.locator('#close-player').click()
        older={**dataset,'dataset_id':'older-browser-test','season':'2025-26'}
        unknown_projection={**projection,'draft_status':'unknown','keeper_franchise':None,'confirmed_keeper_cost':None}
        page.route('**/api/projections?*',lambda route:route.fulfill(json={'dataset':older,'rows':[unknown_projection]}))
        page.locator('[data-view="projections"]').click()
        expect(page.locator('#draft-filter')).to_have_value('all')
        expect(page.locator('.dataset-header')).to_contain_text('2025–26')
        expect(page.locator('#data-table')).to_contain_text('Keeper list not supplied')
        assert not errors, errors
        print('PASS: desktop/mobile layouts, history, three valuation outputs, sortable positions/stats, supplied forecasts, category bars, real comps, scenarios, CSV downloads, synthetic fixtures, keeper budgets, availability, season isolation. No browser errors.')
        browser.close()


if __name__=='__main__':
    main()
